### ISSUE TITLE
issues about the Eq.(1)(2) in the paper

### ISSUE THREAD

**Issue by Dawn-LX** [FingerRec/OA-Transformer#1]
hello , i am following your work, and i find some problem in your paper https://arxiv.org/pdf/2112.00656v3.pdf

the equation (1) & (2) are exactly the same.

i suppose that in Eq.(2) the item of summation in the denominator should be `exp(sim(t^i,v))`

**Comment by FingerRec** [comment]
Thanks for your response! I'll update this typos in arxiv.  👍
