### ISSUE TITLE
config to run frozen-in-time baseline

### ISSUE THREAD

**Issue by xiyinmsu** [FingerRec/OA-Transformer#4]
Hi, this work is very interesting! Thanks for releasing the code.

In the paper, you have mentioned that your implementation of frozen-in-time leads to better results. Do you have a config file to run frozen-in-time baseline in your repo.? Thanks.

**Comment by FingerRec** [comment]
Hello, thanks for the interest in our work.

I have update the baseline config in OATrans/pt/cc3m_webvid/norm.json
