### ISSUE TITLE
Could you share this file please? thanks.

### ISSUE THREAD

**Issue by xiyinmsu** [FingerRec/OA-Transformer#7]
https://github.com/FingerRec/OA-Transformer/blob/e38bc99d03ceec5f7ae4d5a072555f82b80d4d39/OATrans/base/base_dataset_region_mem.py#L298

**Comment by FingerRec** [comment]
really sorry for late reply.

I have uploaded this file to [google driver](https://drive.google.com/drive/folders/1hUqVZAEWbN9uoiaFUeDCj4bgYhiBpa6K?usp=sharing).
